Repository mistweaverco/kulala.nvim, pull requests merged in 2024-09, with the labels that each got.

#203 feat(vars): add prompt variables
  docs/docs/usage/using-variables.md
  lua/kulala/cmd/init.lua
  lua/kulala/internal_processing/init.lua
Labels: enhancement

#204 fix(prompt-vars): run parser after prompt vars
  lua/kulala/cmd/init.lua
  lua/kulala/ui/init.lua
Labels: bug

#206 Feat/fenced code blocks
  lua/kulala/parser/init.lua
  lua/kulala/utils/fs.lua
Labels: enhancement

#210 fix(ui/parser): remove unused variable, remove nil warnings
  lua/kulala/parser/init.lua
  lua/kulala/ui/init.lua
Labels: enhancement

#215 feat(checkhealth): support for neovim :checkhealth feature
  lua/kulala/health.lua
Labels: enhancement

#212 feat(ci): test support via plenary test harness
  .github/workflows/tests.yml
  .gitignore
  lua/kulala/parser/curl.lua
  scripts/tests.sh
  tests/init.vim
  tests/minimal_init.lua
  tests/parser/curl_spec.lua
Labels: enhancement

#217 fix(replay)
  lua/kulala/cmd/init.lua
Labels: bug

#218 feat(ci): use custom image for tests
  .github/workflows/tests.yml
  scripts/tests.sh
  tests/_dockerfiles/ubuntu/Dockerfile
Labels: enhancement

#219 Change testing framework to busted
  .github/workflows/tests.yml
  .gitignore
  scripts/tests.sh
  tests/_dockerfiles/ubuntu/Dockerfile
  tests/init.vim
  tests/minimal_init.lua
  tests/minit.lua
Labels: enhancement

#216 Environment Scope
  docs/docs/getting-started/configuration-options.md
  lua/kulala/config/init.lua
  lua/kulala/db/init.lua
  lua/kulala/external_processing/init.lua
  lua/kulala/internal_processing/init.lua
  lua/kulala/parser/env.lua
  lua/kulala/parser/init.lua
  lua/kulala/parser/request_variables.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/selector.lua
  lua/telescope/_extensions/kulala.lua
  tests/db/db_spec.lua
Labels: enhancement

#201 implement response redirect with treesitter
  lua/kulala/parser/init.lua
  lua/kulala/parser/treesitter.lua
  lua/kulala/ui/init.lua
Labels: enhancement

#221 fix(parser): trimming lines caused troubles
  lua/kulala/parser/graphql.lua
  lua/kulala/parser/init.lua
Labels: bug

#208 Feat/add best practices doc
  docs/docs/getting-started/configuration-options.md
  docs/docs/getting-started/example-configuration.md
  docs/sidebars.ts
Labels: documentation

#227 fix(docs): example
  docs/docs/getting-started/example-configuration.md
Labels: documentation

#230 fix(form): fix binary multipart-form-data
  docs/docs/usage/sending-form-data.md
  lua/kulala/parser/init.lua
  lua/kulala/utils/fs.lua
Labels: bug

#233 chore(npm): update packages 📦
  docs/package-lock.json
  docs/package.json
Labels: dependencies

#235 fix(gql): introspection curl path
  lua/kulala/graphql/init.lua
Labels: bug

#229 fix(shlex): make split function more robust
  lua/kulala/lib/shlex/init.lua
  tests/lib/shlex/shlex_spec.lua
Labels: enhancement

#237 fix(health): support curl_path in a healthcheck
  lua/kulala/health.lua
Labels: bug

#238 fix(from_curl): improve heuristic and recognize curl_path too
  lua/kulala/parser/curl.lua
Labels: enhancement

#239 Output path to curl executable and version in checkhealth
  lua/kulala/health.lua
  lua/kulala/utils/fs.lua
Labels: enhancement

#249 fix(ui): treesitter foldexpr calculate not work
  lua/kulala/ui/init.lua
Labels: bug

#250 fix(parser): handle exception when no reqs found
  lua/kulala/parser/init.lua
Labels: enhancement

#243 feat: add json schema for http-client.env.json
  .gitignore
  docs/docs/getting-started/configuration-options.md
  docs/docs/usage/dotenv-and-http-client.env.json-support.md
  lua/kulala/db/init.lua
  lua/kulala/parser/env.lua
  lua/kulala/parser/init.lua
  lua/kulala/ui/selector.lua
  lua/telescope/_extensions/kulala.lua
  schemas/http-client.env.schema.json
Labels: breaking-change

#251 docs(http-client.env): add docs for `.private.json`.
  docs/docs/usage/dotenv-and-http-client.env.json-support.md
  lua/kulala/parser/env.lua
  lua/kulala/parser/init.lua
  schemas/http-client.private.env.schema.json
Labels: enhancement
