Repository mistweaverco/kulala.nvim, pull requests merged in 2024-08, with the labels that each got.

#91 fix(env): early return causing nil env table error
  lua/kulala/parser/env.lua
Labels: bug

#93 feat(parser): named-requests + request-variables + `replay()`
  docs/docs/usage/public-methods.md
  docs/docs/usage/request-variables.md
  lua/kulala/cmd/init.lua
  lua/kulala/db/init.lua
  lua/kulala/external_processing/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/init.lua
  lua/kulala/internal_processing/init.lua
  lua/kulala/parser/env.lua
  lua/kulala/parser/init.lua
  lua/kulala/parser/request_variables.lua
  lua/kulala/ui/init.lua
  package.json
Labels: enhancement

#94 feat: add search()
  docs/docs/usage/public-methods.md
  lua/kulala/init.lua
  lua/kulala/ui/selector.lua
  lua/kulala/utils/fs.lua
  lua/telescope/_extensions/kulala.lua
Labels: enhancement

#95 Update README.md
  README.md
Labels: documentation

#96 chore(cleanup): rm package(-lock).json
  package-lock.json
  package.json
  scripts/set-version.sh
Labels: enhancement

#98 feat(parser): lazy-eval doc-variables
  lua/kulala/parser/init.lua
Labels: enhancement

#97 Update install.md
  docs/docs/getting-started/install.md
Labels: documentation

#99 feat(ui): add scratchpad
  docs/docs/getting-started/setup-options.md
  docs/docs/usage/automatic-response-formatting.md
  docs/docs/usage/dotenv-and-http-client.env.json-support.md
  docs/docs/usage/public-methods.md
  docs/docs/usage/request-variables.md
  lua/kulala/config/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/init.lua
  lua/kulala/ui/init.lua
Labels: enhancement

#103 feat(parser): graphql -> same syntax as vscode
  docs/docs/usage/graphql.md
  lua/kulala/parser/graphql.lua
Labels: enhancement

#104 feat(parser): use magic gql vscode header as fallback
  lua/kulala/parser/init.lua
Labels: enhancement

#108 Basic, Digest, NTLM, Negotiate Auth by Curl
  docs/docs/usage/authentication.md
  lua/kulala/parser/init.lua
Labels: enhancement

#106 feat: add winbar for result buffer
  lua/kulala/config/init.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/winbar.lua
Labels: enhancement

#116 chore: remove incorrect comment
  lua/kulala/ui/winbar.lua
Labels: bug

#117 fix(parser): req-vars array access
  lua/kulala/parser/request_variables.lua
Labels: bug

#119 Refactor authorization header parsing
  lua/kulala/parser/init.lua
Labels: bug

#120 Add the option to show both headers and body
  docs/docs/getting-started/setup-options.md
  lua/kulala/config/init.lua
  lua/kulala/ui/init.lua
Labels: enhancement

#122 fix: split headers into key value at first colon
  lua/kulala/parser/init.lua
Labels: bug

#125 feat(gql): add schema download
  .gitignore
  .luarc.json
  docs/docs/usage/graphql.md
  lua/kulala/cmd/init.lua
  lua/kulala/graphql/init.lua
  lua/kulala/init.lua
  lua/kulala/logger/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/parser/utils.lua
  lua/kulala/ui/init.lua
  lua/kulala/utils/fs.lua
Labels: enhancement

#126 fix(lint): stylua
  lua/kulala/config/init.lua
  lua/kulala/inlay/init.lua
  lua/kulala/jumps/init.lua
  lua/kulala/parser/request_variables.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/winbar.lua
  lua/kulala/utils/string.lua
  lua/kulala/utils/table.lua
Labels: enhancement

#127 Docs: fix content_types -> contenttypes
  docs/docs/getting-started/setup-options.md
Labels: documentation

#130 fix(ui): replace buffer when content changes
  lua/kulala/config/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/ui/init.lua
Labels: bug

#131 chore(docs): update setup-options.md
  docs/docs/getting-started/setup-options.md
  lua/kulala/config/init.lua
Labels: documentation

#133 fix ext-processing + add jwt example
  docs/docs/usage/dynamically-setting-environment-variables-based-on-response-json.md
  lua/kulala/cmd/shell_utils.lua
  lua/kulala/external_processing/init.lua
  lua/kulala/globals/init.lua
Labels: enhancement

#135 fix external processing + inlay icon location
  docs/docs/getting-started/setup-options.md
  docs/docs/usage/dynamically-setting-environment-variables-based-on-response-json.md
  lua/kulala/config/init.lua
  lua/kulala/external_processing/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/ui/init.lua
Labels: bug

#134 feat: add option to configure split direction
  docs/docs/getting-started/setup-options.md
  lua/kulala/config/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/ui/init.lua
Labels: enhancement

#137 fix(winbar): keymappings not working anymore
  lua/kulala/globals/init.lua
  lua/kulala/ui/callbacks.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/winbar.lua
Labels: bug

#138 fix(env): parser
  lua/kulala/db/init.lua
  lua/kulala/global_store/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/init.lua
  lua/kulala/parser/env.lua
  lua/kulala/parser/init.lua
  lua/kulala/ui/selector.lua
  lua/telescope/_extensions/kulala.lua
Labels: bug

#141 fix: winbar + default_view
  lua/kulala/globals/init.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/winbar.lua
Labels: bug

#142 Vscode rest client env support
  docs/docs/getting-started/setup-options.md
  lua/kulala/config/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/parser/env.lua
  lua/kulala/utils/fs.lua
Labels: enhancement

#145 fix: set_selected_env() does nothing
  lua/kulala/globals/init.lua
  lua/kulala/init.lua
Labels: bug

#149 fix(gql): introspection
  .gitignore
  lua/kulala/globals/init.lua
  lua/kulala/graphql/introspection.graphql
Labels: bug

#150 feat: add api
  docs/docs/usage/api.md
  docs/sidebars.ts
  lua/kulala/api/init.lua
  lua/kulala/cmd/init.lua
  lua/kulala/globals/init.lua
Labels: enhancement

#152 feat: add cookie parser
  docs/docs/usage/request-variables.md
  lua/kulala/globals/init.lua
  lua/kulala/internal_processing/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/parser/jsonpath.lua
  lua/kulala/parser/request_variables.lua
Labels: enhancement

#151 Update lazy.nvim instruction in README.md
  README.md
  docs/docs/getting-started/configuration-options.md
  docs/docs/getting-started/install.md
  docs/docs/usage/dotenv-and-http-client.env.json-support.md
  docs/docs/usage/public-methods.md
  docs/sidebars.ts
Labels: documentation

#153 Fix url parsing bug
  lua/kulala/parser/init.lua
Labels: bug

#165 feat: support AWS-SigV4 authentication
  docs/docs/usage/authentication.md
  lua/kulala/parser/init.lua
Labels: enhancement

#168 fix(authparser): already encoded strings
  lua/kulala/parser/init.lua
Labels: bug

#169 fix(auth): ntlm and negotiate
  lua/kulala/parser/init.lua
Labels: bug

#154 Enable pre- and post-request scripting support.
  docs/docs/scripts/client-reference.md
  docs/docs/scripts/overview.md
  docs/docs/scripts/request-reference.md
  docs/docs/scripts/response-reference.md
  docs/docs/usage/authentication.md
  docs/docs/usage/dynamically-setting-environment-variables-based-on-response-json.md
  docs/docs/usage/public-methods.md
  docs/docusaurus.config.ts
  docs/sidebars.ts
  lua/kulala/cmd/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/init.lua
  lua/kulala/parser/env.lua
  lua/kulala/parser/init.lua
  lua/kulala/scripts/init.lua
  lua/kulala/scripts/javascript.lua
  lua/kulala/scripts/post_request_base.js
  lua/kulala/scripts/pre_request_base.js
  lua/kulala/scripts/utils.lua
  lua/kulala/utils/fs.lua
Labels: enhancement

#166 feat: add `run_all()`
  docs/docs/usage/public-methods.md
  lua/kulala/cmd/init.lua
  lua/kulala/init.lua
  lua/kulala/inlay/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/ui/init.lua
Labels: enhancement

#171 fix(scripts): node_modules path local to script.cwd
  lua/kulala/scripts/javascript.lua
  lua/kulala/utils/fs.lua
Labels: bug

#173 fix(fs): Compatible with "/" and "\\"
  lua/kulala/scripts/javascript.lua
  lua/kulala/utils/fs.lua
Labels: bug

#174 feat(copy): clean and fix
  lua/kulala/ui/init.lua
Labels: enhancement

#175 feat(parser): add inspect
  docs/docs/usage/public-methods.md
  lua/kulala/init.lua
  lua/kulala/parser/inspect.lua
  lua/kulala/ui/init.lua
Labels: enhancement

#177 feat(scripts): print output
  lua/kulala/scripts/javascript.lua
Labels: enhancement

#179 feat(redir-response)
  docs/docs/usage/redirect-the-response.md
  docs/sidebars.ts
  lua/kulala/cmd/init.lua
  lua/kulala/internal_processing/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/utils/fs.lua
Labels: enhancement

#181 parse requests with treesitter
  lua/kulala/config/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/parser/treesitter.lua
Labels: enhancement

#187 Standardize the code format
  .editorconfig
  stylua.toml
Labels: enhancement

#190 feat(telescope): add telescope sorter
  lua/telescope/_extensions/kulala.lua
Labels: enhancement

#193 Treesitter Parsing (again)
  lua/kulala/config/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/parser/inspect.lua
  lua/kulala/parser/treesitter.lua
  lua/kulala/ui/init.lua
Labels: enhancement

#195 feat(req-blocks): optional comments
  lua/kulala/parser/init.lua
Labels: enhancement

#196 fix(ts): error on startup
  lua/kulala/parser/treesitter.lua
Labels: bug

#197 Feature/add console winbar
  docs/docs/getting-started/configuration-options.md
  docs/docs/scripts/overview.md
  lua/kulala/config/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/scripts/javascript.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/winbar.lua
  lua/kulala/utils/fs.lua
Labels: enhancement

#199 Add `show_stats()` with ascii diagram
  docs/docs/usage/public-methods.md
  lua/kulala/cmd/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/init.lua
  lua/kulala/parser/curl-format.json
  lua/kulala/parser/init.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/winbar.lua
  lua/kulala/utils/ascii.lua
Labels: enhancement

#200 fix(stats): blank string + run_all
  lua/kulala/cmd/init.lua
Labels: bug

#198 Fix/pre script output error
  lua/kulala/parser/init.lua
  lua/kulala/scripts/javascript.lua
  lua/kulala/ui/init.lua
Labels: bug
