Repository mistweaverco/kulala.nvim, pull requests merged in 2024-10, with the labels that each got.

#252 Improve scripts
  docs/docs/scripts/client-reference.md
  docs/docs/scripts/request-reference.md
  docs/docs/scripts/response-reference.md
  lua/kulala/cmd/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/parser/scripts/engines/javascript/init.lua
  lua/kulala/parser/scripts/engines/javascript/lib/dist/.gitignore
  lua/kulala/parser/scripts/engines/javascript/lib/eslint.config.cjs
  lua/kulala/parser/scripts/engines/javascript/lib/package-lock.json
  lua/kulala/parser/scripts/engines/javascript/lib/package.json
  lua/kulala/parser/scripts/engines/javascript/lib/rollup.config.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/Client.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PostRequestResponse.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PreRequestRequest.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/post_request.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/pre_request.ts
  lua/kulala/parser/scripts/engines/javascript/lib/tsconfig.json
  lua/kulala/parser/scripts/init.lua
  lua/kulala/parser/scripts/javascript/init.lua
  lua/kulala/parser/scripts/utils/init.lua
  lua/kulala/scripts/init.lua
  lua/kulala/scripts/javascript.lua
  lua/kulala/scripts/post_request_base.js
  lua/kulala/scripts/pre_request_base.js
  lua/kulala/utils/fs.lua
Labels: enhancement

#254 fix: resolve "no such file or directory" error in scratchpad
  lua/kulala/globals/init.lua
  lua/kulala/parser/scripts/engines/javascript/init.lua
Labels: bug

#257 fix(scripts): only process if not empty
  lua/kulala/parser/scripts/engines/javascript/init.lua
Labels: bug

#259 feat(parser): streamline globals
  lua/kulala/parser/init.lua
Labels: enhancement

#260 feat(headers): use as supplied + support multiple headers
  lua/kulala/cmd/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/internal_processing/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/parser/utils.lua
Labels: enhancement

#261 fix(scripts): remove lowercase headers access
  docs/docs/usage/public-methods.md
  lua/kulala/globals/init.lua
  lua/kulala/init.lua
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PostRequestResponse.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PreRequestRequest.ts
  lua/kulala/utils/fs.lua
Labels: breaking-change

#262 feat(scripts): add `request.body.getComputed()`
  docs/docs/scripts/request-reference.md
  lua/kulala/globals/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PreRequestRequest.ts
  lua/kulala/utils/fs.lua
Labels: enhancement

#263 feat(ci): add tag script
  Makefile
  scripts/tag.sh
Labels: enhancement

#264 feat(docs): fix CODEOWNERS, add CODE_OF_CONDUCT & CONTRIBUTING
  .github/CODEOWNERS
  CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#265 feat(docs): fix typo in CONTRIB
  CONTRIBUTING.md
Labels: documentation

#267 feat(ci): testrunner clipboard support
  tests/_dockerfiles/ubuntu/Dockerfile
Labels: enhancement

#266 test(ui): add tests for from_curl() and close()
  lua/kulala/ui/init.lua
  tests/test_helper/ui.lua
  tests/ui/init_spec.lua
Labels: enhancement

#272 fix(env): selector without telescope
  lua/kulala/globals/init.lua
  lua/kulala/ui/selector.lua
Labels: bug

#277 fix(graphql): add a Content-Type: application/json if not specified
  lua/kulala/graphql/init.lua
Labels: enhancement

#278 fix(parser): form-data + binary
  docs/docs/usage/sending-form-data.md
  lua/kulala/parser/init.lua
  lua/kulala/parser/inspect.lua
  lua/kulala/utils/fs.lua
Labels: bug

#279 fix(ui): folds not working in lazy
  lua/kulala/ui/init.lua
Labels: bug

#280 feat(search): searching for named requests now
  docs/docs/usage/public-methods.md
  lua/kulala/parser/init.lua
  lua/kulala/parser/utils.lua
  lua/kulala/ui/selector.lua
  lua/telescope/_extensions/kulala.lua
Labels: enhancement

#286 fix(scratchpad): noswapfile
  lua/kulala/ui/init.lua
Labels: bug

#293 docs: add stats to available winbar panes
  docs/docs/getting-started/configuration-options.md
  lua/kulala/config/init.lua
Labels: documentation
