Repository mistweaverco/kulala.nvim, pull requests merged in 2024-07, with the labels that each got.

#32 feat: add custom additional curl opts
  README.md
  docs/_coverpage.md
  docs/install.md
  lua/kulala/config/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/parser/init.lua
  package.json
Labels: enhancement

#33 fix(fs): infinite loop on windows
  docs/_coverpage.md
  lua/kulala/globals/init.lua
  lua/kulala/utils/fs.lua
  package.json
Labels: bug

#38 fix: config-reset
  lua/kulala/config/init.lua
  lua/kulala/formatter/init.lua
  lua/kulala/init.lua
  lua/kulala/inlay/init.lua
  lua/kulala/parser/dynamic_vars.lua
  lua/kulala/parser/init.lua
  lua/kulala/ui/init.lua
  lua/lualine/components/kulala.lua
Labels: bug

#42 make cmd non-blocking
  docs/_coverpage.md
  lua/kulala/cmd/init.lua
  lua/kulala/config/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/inlay/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/ui/init.lua
  lua/kulala/utils/fs.lua
  package.json
Labels: enhancement

#44 fix(env): accessing env-variables
  docs/_coverpage.md
  lua/kulala/globals/init.lua
  lua/kulala/parser/init.lua
  package.json
Labels: bug

#46 feat(parser): verbosity on fail
  docs/_coverpage.md
  lua/kulala/globals/init.lua
  lua/kulala/parser/init.lua
  package.json
Labels: enhancement

#47 Feat complete rewrite parser
  docs/_coverpage.md
  lua/kulala/client_pipe/init.lua
  lua/kulala/cmd/init.lua
  lua/kulala/formatter/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/init.lua
  lua/kulala/jumps/init.lua
  lua/kulala/parser/dynamic_vars.lua
  lua/kulala/parser/init.lua
  lua/kulala/utils/table.lua
  package.json
Labels: breaking-change

#49 fix: allow other content types to be used
  docs/_coverpage.md
  lua/kulala/globals/init.lua
  lua/kulala/parser/init.lua
  package.json
Labels: bug

#50 Feature: Add metatags and add ability to process responses externally
  .luacheckrc
  docs/_coverpage.md
  lua/kulala/client_pipe/init.lua
  lua/kulala/cmd/init.lua
  lua/kulala/external_processing/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/parser/init.lua
  package.json
Labels: enhancement

#52 feat: move to docusaurus
  .github/workflows/pages.yml
  docs/.gitignore
  docs/README.md
  docs/_coverpage.md
  docs/_sidebar.md
  docs/babel.config.js
  docs/docs/http_file_spec.md
  docs/docs/install.md
  docs/docs/logo.svg
  docs/docs/public_methods.md
  docs/docs/requirements.md
  docs/docs/usage.md
  docs/docusaurus.config.ts
  docs/index.html
  docs/package-lock.json
  docs/package.json
  docs/sidebars.ts
  docs/src/components/Badges/index.tsx
  docs/src/components/Badges/styles.module.css
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/src/pages/markdown-page.md
  docs/static/.nojekyll
  docs/static/img/favicon.png
  docs/static/img/favicon.svg
  docs/static/img/logo.svg
  docs/tsconfig.json
  package.json
Labels: enhancement

#53 feat: add internal processing
  docs/docs/http_file_spec.md
  docs/docs/install.md
  docs/docs/public_methods.md
  docs/docs/requirements.md
  docs/docs/setup-options.md
  docs/docs/usage.md
  docs/docs/usage/authentication.md
  docs/docs/usage/dotenv-and-http-client.env.json-support.md
  docs/docs/usage/dynamically-setting-environment-variables-based-on-response-json.md
  docs/docs/usage/index.md
  docs/docs/usage/sending-form-data.md
  docs/docs/usage/using-environment-variables.md
  docs/docs/usage/using-variables.md
  lua/kulala/cmd/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/internal_processing/init.lua
  package.json
  scripts/set-version.sh
Labels: enhancement

#56 fix(parser): document variables with underscores
  lua/kulala/globals/init.lua
  lua/kulala/parser/init.lua
  package.json
Labels: bug

#57 fix(autocmd): add augroup
  lua/kulala/globals/init.lua
  lua/kulala/ui/init.lua
  package.json
Labels: bug

#59 feat(parser): add inline graphql support
  lua/kulala/parser/graphql.lua
  lua/kulala/parser/init.lua
Labels: enhancement

#62 chore(docs): add magic-variables + formatting
  docs/docs/usage/automatic-response-formatting.md
  docs/docs/usage/magic-variables.md
  lua/kulala/parser/dynamic_vars.lua
Labels: documentation

#64 feat(env): add DEFAULT_HEADERS
  docs/docs/usage/dotenv-and-http-client.env.json-support.md
  lua/kulala/globals/init.lua
  lua/kulala/parser/env.lua
  lua/kulala/parser/init.lua
  lua/kulala/ui/selector.lua
  lua/telescope/_extensions/kulala.lua
  package.json
Labels: enhancement

#68 feat: add `.copy()` function
  docs/docs/public_methods.md
  lua/kulala/globals/init.lua
  lua/kulala/init.lua
  lua/kulala/ui/init.lua
  package.json
Labels: enhancement

#69 fix(parser): don't set data when body is nil
  lua/kulala/globals/init.lua
  lua/kulala/parser/init.lua
  package.json
Labels: bug

#73 feat(parser): add @file-to-variable meta-tag
  docs/docs/usage/file-to-variable.md
  lua/kulala/globals/init.lua
  lua/kulala/parser/init.lua
  package.json
Labels: enhancement

#76 chore(docs): update to match kulala-fmt
  docs/docs/http_file_spec.md
  docs/docs/usage/graphql.md
  docs/docs/usage/magic-variables.md
  docs/docs/usage/sending-form-data.md
  docs/docs/usage/using-environment-variables.md
  docs/docs/usage/using-variables.md
  lua/kulala/parser/init.lua
Labels: documentation

#77 feat(ui): add `close()` function
  docs/docs/public_methods.md
  lua/kulala/globals/init.lua
  lua/kulala/init.lua
  lua/kulala/ui/init.lua
  package.json
Labels: enhancement

#79 fix(docs): fix README links to docs
  README.md
Labels: documentation

#86 fix(fs): avoid infinite loop searching parent dir
  lua/kulala/utils/fs.lua
Labels: bug

#89 feat(parser): add env-header-key meta tag
  docs/docs/usage/dynamically-setting-environment-variables-based-on-headers.md
  docs/docs/usage/dynamically-setting-environment-variables-based-on-response-json.md
  docs/sidebars.ts
  lua/kulala/cmd/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/internal_processing/init.lua
  package.json
Labels: enhancement

#90 fix(fs): find nearest file
  lua/kulala/globals/init.lua
  lua/kulala/utils/fs.lua
  package.json
Labels: bug
