Repository mistweaverco/kulala.nvim, pull requests merged in 2025-04, with the labels that each got.

#427 feat(doc): add runnable http demo
  .gitignore
  NEWS.md
  README.md
  docs/docs/getting-started/configuration-options.mdx
  docs/docs/getting-started/requirements.md
  docs/docs/usage/basic-usage.md
  docs/docs/usage/demos.mdx
  docs/docs/usage/dotenv-and-http-client.env.json-support.md
  docs/docs/usage/graphql.md
  docs/docs/usage/http-file-spec.md
  docs/docs/usage/import-and-run-http.md
  docs/docs/usage/reading-file-data.md
  docs/package-lock.json
  docs/package.json
  docs/sidebars.ts
  docs/static/demos/1.basic.http
  docs/static/demos/2.variables.http
  docs/static/demos/3.access-token.http
  docs/static/demos/4.cookie.http
  docs/static/demos/5.script.http
  docs/static/demos/6.body-from-file.http
  docs/static/demos/7.testing-and-reporting.http
  docs/static/demos/TOKEN.txt
  docs/static/demos/body-from-file.json
  docs/static/demos/demos.zip
  docs/static/demos/http-client.env.json
  docs/static/demos/post-request.js
  docs/static/import/defaults.lua
  lua/kulala/config/defaults.lua
  lua/kulala/config/init.lua
  lua/kulala/logger/init.lua
Labels: documentation, enhancement

#439 Feat: add support for multiline URLs
  lua/kulala/parser/document.lua
  tests/functional/parser_spec.lua
Labels: enhancement

#430 Feat: $auth.token for Oauth2 support
  .gitignore
  Makefile
  docs/docs/usage/authentication.md
  docs/vale.ini
  lua/kulala/cmd/crypto.lua
  lua/kulala/cmd/oauth.lua
  lua/kulala/config/init.lua
  lua/kulala/config/keymaps.lua
  lua/kulala/db/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/health.lua
  lua/kulala/init.lua
  lua/kulala/parser/document.lua
  lua/kulala/parser/dynamic_vars.lua
  lua/kulala/parser/env.lua
  lua/kulala/parser/scripts/engines/javascript/init.lua
  lua/kulala/ui/auth_manager.lua
  lua/kulala/ui/env_manager.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/request_manager.lua
  lua/kulala/utils/fs.lua
  lua/kulala/utils/json.lua
  lua/kulala/utils/table.lua
  lua/telescope/_extensions/kulala.lua
  tests/functional/oauth_spec.lua
  tests/functional/requests/http-client.env.default.json
  tests/functional/requests/http-client.env.json
  tests/functional/requests/http-client.private.env.default.json
  tests/functional/requests/http-client.private.env.json
  tests/functional/requests/oauth.http
Labels: enhancement

#446 fix(ui): fallback to ui.select if no telescope/snacks
  lua/kulala/init.lua
  lua/kulala/ui/auth_manager.lua
  lua/kulala/ui/env_manager.lua
  lua/kulala/ui/request_manager.lua
  lua/kulala/ui/selector.lua
Labels: bug

#447 Add a workflow to auto generate vimdocs and vimtags
  .github/workflows/vimdocs.yml
  Makefile
  NEWS.md
  README.md
  doc/kulala.NEWS.txt
  doc/kulala.README.txt
  doc/kulala.authentication.txt
  doc/kulala.automatic-response-formatting.txt
  doc/kulala.basic-usage.txt
  doc/kulala.client-reference.txt
  doc/kulala.configuration-options.txt
  doc/kulala.default-keymaps.txt
  doc/kulala.demos.txt
  doc/kulala.dotenv-and-http-client.env.json-support.txt
  doc/kulala.dynamically-setting-environment-variables-based-on-response-json.txt
  doc/kulala.graphql.txt
  doc/kulala.grpc.txt
  doc/kulala.http-file-spec.txt
  doc/kulala.import-and-run-http.txt
  doc/kulala.index.txt
  doc/kulala.install.txt
  doc/kulala.keymaps.txt
  doc/kulala.overview.txt
  doc/kulala.public-methods.txt
  doc/kulala.request-reference.txt
  doc/kulala.request-variables.txt
  doc/kulala.requirements.txt
  doc/kulala.testing-and-reporting.txt
  doc/kulala.websockets.txt
  doc/tags
  docs/docs/index.md
  docs/docs/usage/index.md
  docs/package-lock.json
  docs/package.json
  lua/kulala/ui/init.lua
  scripts/pandoc/build-toc.lua
  scripts/pandoc/panvimdoc.lua
  scripts/pandoc/panvimdoc.sh
  scripts/vimdocs.sh
Labels: documentation

#453 Feat: autocomplete
  lua/kulala/config/defaults.lua
  lua/kulala/config/init.lua
  lua/kulala/ui/auth_manager.lua
  lua/kulala/utils/complete.lua
  lua/kulala/utils/table.lua
Labels: enhancement

#455 Feat/update docker
  .github/workflows/tests.yml
  .github/workflows/vimdocs.yml
  Makefile
  tests/_dockerfiles/linux/Dockerfile
  tests/_dockerfiles/linux/README.md
Labels: enhancement

#451 Feat: per-request and global @curl flags
  .gitignore
  NEWS.md
  doc/kulala.NEWS.txt
  doc/kulala.basic-usage.txt
  doc/kulala.custom-curl-flags.txt
  doc/kulala.dotenv-and-http-client.env.json-support.txt
  doc/kulala.index.txt
  doc/tags
  docs/docs/index.md
  docs/docs/usage/basic-usage.md
  docs/docs/usage/custom-curl-flags.md
  docs/docs/usage/dotenv-and-http-client.env.json-support.md
  docs/sidebars.ts
  lua/kulala/config/keymaps.lua
  lua/kulala/parser/document.lua
  lua/kulala/parser/env.lua
  lua/kulala/parser/request.lua
  lua/kulala/parser/string_variables_parser.lua
  lua/kulala/ui/auth_manager.lua
  lua/kulala/ui/env_manager.lua
  lua/kulala/ui/init.lua
  scripts/pandoc/build-toc.lua
  tests/functional/fixtures/advanced_B_request.txt
  tests/functional/fixtures/advanced_D_request.txt
  tests/functional/fixtures/simple_request.txt
  tests/functional/parser_spec.lua
  tests/functional/requests/http-client.env.default.json
  tests/functional/requests/http-client.env.json
  tests/functional/requests/http-client.private.env.json
Labels: enhancement

#449 Feat(ui): Request progress and Request interrupt
  NEWS.md
  lua/kulala/cmd/init.lua
  lua/kulala/cmd/websocket.lua
  lua/kulala/config/keymaps.lua
  lua/kulala/db/init.lua
  lua/kulala/inlay/init.lua
  lua/kulala/ui/float.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/request_manager.lua
Labels: enhancement

#454 Feat: Lua scripting
  .gitignore
  NEWS.md
  README.md
  doc/kulala.NEWS.txt
  doc/kulala.README.txt
  doc/kulala.basic-usage.txt
  doc/kulala.configuration-options.txt
  doc/kulala.custom-curl-flags.txt
  doc/kulala.default-keymaps.txt
  doc/kulala.dotenv-and-http-client.env.json-support.txt
  doc/kulala.index.txt
  doc/kulala.lua-scripts.txt
  doc/kulala.overview.txt
  doc/kulala.testing-and-reporting.txt
  docs/docs/getting-started/default-keymaps.md
  docs/docs/scripts/lua-scripts.md
  docs/docs/scripts/overview.md
  docs/docs/usage/basic-usage.md
  docs/docs/usage/custom-curl-flags.md
  docs/docs/usage/dotenv-and-http-client.env.json-support.md
  docs/docs/usage/testing-and-reporting.md
  docs/sidebars.ts
  docs/static/import/defaults.lua
  lua/kulala/cmd/init.lua
  lua/kulala/config/defaults.lua
  lua/kulala/config/init.lua
  lua/kulala/db/init.lua
  lua/kulala/parser/document.lua
  lua/kulala/parser/request.lua
  lua/kulala/parser/scripts/engines/javascript/init.lua
  lua/kulala/parser/scripts/init.lua
  lua/kulala/parser/scripts/lua/init.lua
  lua/kulala/parser/string_variables_parser.lua
  lua/kulala/queries/injections.scm
  lua/kulala/ui/treesitter.lua
  lua/kulala/utils/complete.lua
  lua/kulala/utils/fs.lua
  lua/kulala/utils/json.lua
  scripts/pandoc/build-toc.lua
  scripts/tests.sh
  scripts/vimdocs.sh
  tests/functional/oauth_spec.lua
  tests/functional/requests/http-client.env.json
  tests/functional/requests/http-client.private.env.json
  tests/functional/requests_spec.lua
  tests/functional/scripts/post_script.lua
  tests/functional/scripts/pre_script.lua
Labels: enhancement

#466 Feat: LSP
  NEWS.md
  README.md
  doc/kulala.NEWS.txt
  doc/kulala.README.txt
  doc/kulala.automatic-response-formatting.txt
  doc/kulala.basic-usage.txt
  doc/kulala.custom-curl-flags.txt
  doc/kulala.dotenv-and-http-client.env.json-support.txt
  doc/kulala.grpc.txt
  doc/kulala.import-and-run-http.txt
  doc/kulala.index.txt
  doc/kulala.install.txt
  doc/kulala.lua-scripts.txt
  doc/kulala.overview.txt
  doc/kulala.public-methods.txt
  doc/kulala.request-reference.txt
  doc/kulala.request-variables.txt
  doc/kulala.testing-and-reporting.txt
  docs/docs/usage/basic-usage.md
  docs/sidebars.ts
  lua/kulala/utils/complete.lua
  scripts/vimdocs.sh
  tests/functional/parser_spec.lua
Labels: enhancement

#474 fix: fix winbar highlights
  lua/kulala/ui/winbar.lua
Labels: enhancement

#478 refact: make oauth2 requests async
  lua/kulala/cmd/init.lua
  lua/kulala/cmd/oauth.lua
  lua/kulala/cmd/tcp.lua
  lua/kulala/db/init.lua
  lua/kulala/internal_processing/init.lua
  lua/kulala/logger/init.lua
  lua/kulala/parser/document.lua
  lua/kulala/parser/dynamic_vars.lua
  lua/kulala/parser/scripts/engines/javascript/init.lua
  lua/kulala/parser/scripts/init.lua
  lua/kulala/parser/string_variables_parser.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/request_manager.lua
  lua/kulala/utils/async.lua
  tests/functional/oauth_spec.lua
  tests/functional/ui_spec.lua
Labels: enhancement

#490 fix: various fixes
  docs/docs/getting-started/configuration-options.mdx
  docs/docs/scripts/lua-scripts.md
  docs/docs/scripts/overview.md
  docs/docs/scripts/response-reference.md
  docs/docs/usage/authentication.md
  docs/docs/usage/basic-usage.md
  docs/docs/usage/dynamically-setting-environment-variables-based-on-headers.md
  docs/docs/usage/dynamically-setting-environment-variables-based-on-response-json.md
  docs/docs/usage/public-methods.md
  docs/docs/usage/request-variables.md
  docs/static/import/defaults.lua
  docs/static/import/demos/3.access-token.http
  docs/static/import/demos/4.cookie.http
  docs/static/import/demos/5.script.http
  lua/kulala/cmd/init.lua
  lua/kulala/config/defaults.lua
  lua/kulala/db/init.lua
  lua/kulala/init.lua
  lua/kulala/internal_processing/init.lua
  lua/kulala/parser/document.lua
  lua/kulala/parser/request.lua
  lua/kulala/parser/request_variables.lua
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PostRequestResponse.ts
  lua/kulala/parser/scripts/lua/init.lua
  lua/kulala/ui/auth_manager.lua
  lua/kulala/ui/env_manager.lua
  lua/kulala/ui/request_manager.lua
  lua/kulala/utils/fs.lua
  schemas/http-client.env.schema.json
  scripts/build_ts.sh
  tests/functional/fixtures/advanced_F_body.txt
  tests/functional/fixtures/advanced_F_headers.txt
  tests/functional/fixtures/cookies.txt
  tests/functional/oauth_spec.lua
  tests/functional/parser_spec.lua
  tests/functional/requests/advanced_F.http
  tests/functional/requests_spec.lua
  tests/functional/scripts/advanced_D_post.js
  tests/functional/ui_spec.lua
  tests/test_helper/stubs.lua
Labels: enhancement
