Repository mistweaverco/kulala.nvim, pull requests merged in 2025-02, with the labels that each got.

#312 fix: result panel didn't show after call
  lua/kulala/ui/init.lua
Labels: bug

#346 Support transfer chunked #332
  lua/kulala/cmd/init.lua
  lua/kulala/db/init.lua
  lua/kulala/graphql/init.lua
  lua/kulala/init.lua
  lua/kulala/inlay/init.lua
  lua/kulala/internal_processing/init.lua
  lua/kulala/parser/env.lua
  lua/kulala/parser/init.lua
  lua/kulala/parser/inspect.lua
  lua/kulala/parser/scripts/engines/javascript/init.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/selector.lua
  lua/kulala/ui/winbar.lua
  lua/kulala/utils/fs.lua
  tests/functional/fixtures/graphql_schema_body.txt
  tests/functional/fixtures/request_1_script.txt
  tests/functional/fixtures/request_1_stats.txt
  tests/functional/fixtures/stats.json
  tests/functional/requests/chunked.http
  tests/functional/requests_spec.lua
  tests/functional/ui_spec.lua
  tests/test_helper/stubs.lua
  tests/test_helper/ui.lua
  tests/ui/init_spec.lua
Labels: enhancement

#349 fix(docs): wrong href for usage manual
  README.md
Labels: documentation

#353 chore(pkg): update node modules for doc gen
  docs/package-lock.json
  docs/package.json
Labels: enhancement, dependencies

#355 fix(cmd): loading icon not shown
  lua/kulala/cmd/init.lua
Labels: bug

#356 feat(ui): flash requests
  lua/kulala/cmd/init.lua
  lua/kulala/ui/highlight.lua
Labels: enhancement

#220 feature: show variable values on hover
  docs/docs/getting-started/configuration-options.md
  lua/kulala/augroups/init.lua
  lua/kulala/config/init.lua
  lua/kulala/init.lua
  lua/kulala/parser/init.lua
  lua/kulala/parser/string_variables_parser.lua
  lua/kulala/ui/float.lua
Labels: enhancement

#357 feat(parser): replace variables also in header name
  lua/kulala/parser/init.lua
Labels: enhancement

#352 Fix: to allow run_all() for visually selected lines (#325)
  lua/kulala/parser/init.lua
  tests/functional/ui_spec.lua
Labels: enhancement

#359 feat(docs): update codeowners
  CODEOWNERS
Labels: documentation

#358 Add default keymaps
  lua/kulala/config/init.lua
  lua/kulala/config/keymaps.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/winbar.lua
  tests/functional/ui_spec.lua
  tests/test_helper/ui.lua
Labels: enhancement

#360 fix(str_var_parser): binary data handling
  lua/kulala/parser/string_variables_parser.lua
Labels: bug

#374 feat(docs): update various docs
  docs/docs/getting-started/configuration-options.md
  docs/docs/getting-started/keymaps.md
  docs/docs/usage/huge-request-body.md
  docs/docs/usage/reading-file-data.md
  docs/docs/usage/sending-form-data.md
  docs/sidebars.ts
Labels: documentation

#373 Show icons in signcolumn
  lua/kulala/cmd/init.lua
  lua/kulala/config/init.lua
  lua/kulala/inlay/init.lua
  lua/kulala/ui/init.lua
Labels: enhancement

#375 Feat/docs
  docs/docs/getting-started/configuration-options.md
  docs/docs/getting-started/keymaps.md
  lua/kulala/config/init.lua
Labels: documentation

#376 Feat: add request/response history
  .gitignore
Labels: enhancement

#380 Fix: do not reopen kulala win in another tab
  lua/kulala/inlay/init.lua
  lua/kulala/ui/init.lua
  tests/functional/requests_spec.lua
Labels: bug

#381 Feat: Custom response handler
  lua/kulala/api/init.lua
  lua/kulala/cmd/init.lua
  lua/kulala/config/init.lua
  lua/kulala/ui/init.lua
  tests/functional/requests_spec.lua
  tests/functional/ui_spec.lua
Labels: enhancement

#378 feat: add grpc support
  .gitignore
  docs/docs/usage/grpc.md
  lua/kulala/cmd/init.lua
  lua/kulala/config/init.lua
  lua/kulala/db/init.lua
  lua/kulala/formatter/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/logger/init.lua
  lua/kulala/parser/document.lua
  lua/kulala/parser/env.lua
  lua/kulala/parser/request.lua
  lua/kulala/utils/fs.lua
  tests/functional/grpc_spec.lua
  tests/functional/keymaps_spec.lua
  tests/functional/parser_spec.lua
  tests/test_helper/stubs.lua
Labels: enhancement

#387 fix(parser): redirect response with overwrite enabled
  lua/kulala/parser/document.lua
Labels: bug

#388 fix(tests): replace hard-coded kulala version
  tests/functional/ui_spec.lua
Labels: bug

#382 Docs UI
  docs/CNAME
  docs/docs/getting-started/configuration-options.md
  docs/docs/getting-started/default-keymaps.md
  docs/docs/getting-started/example-configuration.md
  docs/docs/getting-started/install.md
  docs/docs/getting-started/keymaps.md
  docs/docs/getting-started/requirements.md
  docs/docs/usage/api.md
  docs/docs/usage/basic-usage.md
  docs/docs/usage/file-to-variable.md
  docs/docs/usage/grpc.md
  docs/docs/usage/reading-file-data.md
  docs/docs/usage/streaming-and-transfer-chunked.md
  docs/sidebars.ts
  docs/vale.ini
  lua/kulala/cmd/init.lua
  lua/kulala/config/init.lua
  lua/kulala/config/keymaps.lua
  lua/kulala/db/init.lua
  lua/kulala/parser/document.lua
  lua/kulala/parser/request.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/winbar.lua
  lua/kulala/utils/fs.lua
  scripts/lint.sh
  tests/functional/grpc_spec.lua
  tests/functional/keymaps_spec.lua
  tests/functional/parser_spec.lua
  tests/functional/requests/advanced_C.http
  tests/functional/requests_spec.lua
  tests/functional/ui_spec.lua
Labels: enhancement

#390 fix(docs): related to latest refactoring
  docs/docs/getting-started/configuration-options.md
  docs/docusaurus.config.ts
Labels: documentation

#384 fix(curl parser): multiline body (#383)
  lua/kulala/parser/curl.lua
  lua/kulala/ui/init.lua
  tests/parser/curl_spec.lua
Labels: bug

#397 Feat: replace vars in external json
  lua/kulala/health.lua
  lua/kulala/parser/request.lua
  tests/functional/fixtures/simple.json
  tests/functional/parser_spec.lua
Labels: enhancement

#399 fix(parser): body not overriding computed_body anymore
  lua/kulala/parser/request.lua
Labels: bug
