Repository mistweaverco/kulala.nvim, pull requests merged in 2025-05, with the labels that each got.

#501 Add `global_keymaps_prefix` option to prevent overriding user keymaps
  README.md
  lua/kulala/config/defaults.lua
  lua/kulala/config/keymaps.lua
  tests/functional/keymaps_spec.lua
Labels: enhancement

#541 Improve the user input prompt string
  lua/kulala/internal_processing/init.lua
Labels: enhancement

#536 Fix compatibility with Neovim 0.10+ and older versions
  lua/kulala/ui/float.lua
  lua/kulala/ui/utils.lua
Labels: enhancement

#532 feat: oauth improvements, @curl-data-urlencode, various fixes
  .github/workflows/vimdocs.yml
  NEWS.md
  README.md
  action.yml
  doc/kulala.NEWS.txt
  doc/kulala.README.txt
  doc/kulala.authentication.txt
  doc/kulala.cli-ci.txt
  doc/kulala.custom-curl-flags.txt
  doc/kulala.http-file-spec.txt
  docs/docs/getting-started/configuration-options.mdx
  docs/docs/getting-started/install.md
  docs/docs/getting-started/keymaps.md
  docs/docs/scripts/lua-scripts.md
  docs/docs/scripts/request-reference.md
  docs/docs/usage/authentication.md
  docs/docs/usage/basic-usage.md
  docs/docs/usage/cli-ci.md
  docs/docs/usage/custom-curl-flags.md
  docs/docs/usage/http-file-spec.md
  docs/static/import/demos/5.script.http
  lua/kulala/cmd/init.lua
  lua/kulala/cmd/lsp.lua
  lua/kulala/cmd/oauth.lua
  lua/kulala/config/defaults.lua
  lua/kulala/config/keymaps.lua
  lua/kulala/internal_processing/init.lua
  lua/kulala/parser/document.lua
  lua/kulala/parser/env.lua
  lua/kulala/parser/request.lua
  lua/kulala/parser/request_variables.lua
  lua/kulala/parser/scripts/init.lua
  lua/kulala/parser/scripts/lua/init.lua
  lua/kulala/parser/scripts/utils/init.lua
  lua/kulala/parser/string_variables_parser.lua
  lua/kulala/parser/utils.lua
  lua/kulala/ui/auth_manager.lua
  lua/kulala/ui/float.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/utils.lua
  lua/kulala/ui/winbar.lua
  lua/kulala/utils/fs.lua
  tests/functional/fixtures/request_2_errors_payload.txt
  tests/functional/oauth_spec.lua
  tests/functional/parser_spec.lua
  tests/functional/requests/http-client.private.env.default.json
  tests/functional/requests/http-client.private.env.json
  tests/functional/requests_spec.lua
  tests/functional/ui_spec.lua
Labels: bug, enhancement, needs-windows-test

#552 fix(parser): allow GRAPHQL method
  lua/kulala/cmd/lsp.lua
  lua/kulala/parser/graphql.lua
  lua/kulala/parser/request.lua
  lua/kulala/utils/json.lua
  tests/functional/requests_spec.lua
Labels: fix

#565 fix(parser): vscode settings parse
  lua/kulala/parser/env.lua
Labels: fix
