Repository mistweaverco/kulala.nvim, pull requests merged in 2025-03, with the labels that each got.

#405 Asserts and reporting
  Makefile
  docs/docs/getting-started/configuration-options.md
  docs/docs/getting-started/default-keymaps.md
  docs/docs/scripts/client-reference.md
  docs/docs/scripts/request-reference.md
  docs/docs/scripts/response-reference.md
  docs/docs/usage/basic-usage.md
  docs/docs/usage/testing-and-reporting.md
  docs/sidebars.ts
  docs/static/img/kulala_report.png
  docs/static/img/kulala_ui.png
  lua/kulala/cmd/init.lua
  lua/kulala/config/init.lua
  lua/kulala/config/keymaps.lua
  lua/kulala/db/init.lua
  lua/kulala/globals/init.lua
  lua/kulala/internal_processing/init.lua
  lua/kulala/logger/init.lua
  lua/kulala/parser/curl-format.json
  lua/kulala/parser/request.lua
  lua/kulala/parser/scripts/engines/javascript/init.lua
  lua/kulala/parser/scripts/engines/javascript/lib/.gitignore
  lua/kulala/parser/scripts/engines/javascript/lib/package-lock.json
  lua/kulala/parser/scripts/engines/javascript/lib/rollup.config.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/Assert.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/Client.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PostRequest.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PostRequestResponse.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/lib/PreRequestRequest.ts
  lua/kulala/parser/scripts/engines/javascript/lib/src/post_request.ts
  lua/kulala/parser/string_variables_parser.lua
  lua/kulala/ui/float.lua
  lua/kulala/ui/highlight.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/report.lua
  lua/kulala/ui/utils.lua
  lua/kulala/ui/winbar.lua
  lua/kulala/utils/fs.lua
  scripts/build_ts.sh
  tests/functional/fixtures/report.txt
  tests/functional/fixtures/stats.json
  tests/functional/grpc_spec.lua
  tests/functional/keymaps_spec.lua
  tests/functional/report_spec.lua
  tests/functional/requests/report.http
  tests/functional/requests_spec.lua
  tests/functional/ui_spec.lua
  tests/minit.lua
  tests/test_helper/stubs.lua
  tests/test_helper/ui.lua
Labels: enhancement

#412 FIX: Js update fix
  docs/docs/usage/api.md
  lua/kulala/parser/scripts/engines/javascript/init.lua
  lua/kulala/utils/fs.lua
  tests/functional/ui_spec.lua
Labels: bug

#414 fix: use screen size instead of win size for float
  lua/kulala/ui/init.lua
Labels: enhancement

#417 Feat: add win_opts config option
  docs/docs/getting-started/configuration-options.md
  lua/kulala/config/init.lua
  lua/kulala/ui/init.lua
Labels: enhancement

#422 Fix(parser): replay and comments
  lua/kulala/cmd/init.lua
  lua/kulala/parser/document.lua
  lua/kulala/parser/request.lua
  lua/kulala/utils/table.lua
  scripts/tests.sh
  tests/functional/parser_spec.lua
  tests/functional/ui_spec.lua
Labels: bug, enhancement

#429 Feat: add news hint
  NEWS.md
  lua/kulala/config/init.lua
  lua/kulala/config/keymaps.lua
  lua/kulala/ui/float.lua
  lua/kulala/ui/init.lua
  lua/kulala/ui/report.lua
  lua/kulala/ui/utils.lua
  lua/kulala/utils/fs.lua
Labels: enhancement

#428 Feat: Websockets support
  docs/docs/usage/websockets.md
  docs/sidebars.ts
  lua/kulala/cmd/init.lua
  lua/kulala/cmd/websocket.lua
  lua/kulala/config/init.lua
  lua/kulala/config/keymaps.lua
  lua/kulala/health.lua
  lua/kulala/logger/init.lua
  lua/kulala/ui/init.lua
  tests/functional/websockets_spec.lua
  tests/test_helper/stubs.lua
  tests/test_helper/ui.lua
Labels: enhancement

#425 Fix(ui): do not set signs if signcolumn not used
  lua/kulala/config/init.lua
Labels: bug

#423 Feat: add GRAPHQL method support
  lua/kulala/parser/request.lua
  scripts/tests.sh
  tests/functional/requests_spec.lua
Labels: enhancement

#424 Feat: URL line - comply with IntelliJ spec
  lua/kulala/parser/document.lua
  lua/kulala/parser/request.lua
  lua/kulala/ui/init.lua
  tests/functional/parser_spec.lua
Labels: enhancement

#426 Feat: add import and run commands
  docs/docs/usage/import-and-run-http.md
  docs/sidebars.ts
  lua/kulala/cmd/init.lua
  lua/kulala/parser/document.lua
  lua/kulala/parser/request.lua
  lua/kulala/utils/complete.lua
  lua/kulala/utils/table.lua
  tests/functional/parser_spec.lua
  tests/functional/requests/advanced_A.http
Labels: enhancement

#432 feat(virt_text): use 'combine' to blend with cursorline
  lua/kulala/inlay/init.lua
Labels: enhancement

#434 Fix: winbar keymaps init
  lua/kulala/ui/winbar.lua
Labels: bug
